baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Welcome to Kiaroscuro(?) Kyaroscuro (?) Kjaroskuro (?) Noctilux(?)'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
description = "Intellectual community lmao"

theme = 'auto'
colorPalette = 'default'
hideHeader = false

homeIntroTitle = 'Mankind, Be Vigilant. We Love(d) You'
homeIntroContent = """
Kiaroscuro is a website ==(strongly avoding the word "blog" here, open to suggestions)==

Right so here we go, description: Kiaroscuro is a portal ==(community?)== featuring ==(doesnt sound right)== social criticism and fiction ==(or social critiscism in the form of fiction/prose/short stories/thoughts?)==. Kiaroscuro in essence is a cabinet of thoughts that were put into (prose? sounds a bit too fancy)... ==(to be continued)==

you know what? We need to ponder on WILL this thing actually be, we managed to get this shit going so quick i didint really have time to th0nk on all this.

to do:

-begin the creative **PRÖCESS**
 
-show me had to add new posts

-show me how to highlight things? like in yellow, just change text colours to be able to seperate ideas from actual things on the website</p>

-add paragraph spaces (think i got it?)

-have a drunk brainstorm crunch

-remove herobrine 


"""

homeCollectionTitle = 'Posts'
homeCollection = 'posts'

paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

breadcrumbs = true

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[markup]
[markup.highlight]
style = 'algol'
